---
- name: service module demo
  hosts: ec2
  become: true
  tasks:
        - name:  restarting ssh service
          ansible.builtin.service:
                  name: sshd.service
                  state: restarted
