---
- name: service module demo
  hosts: ec2
  become: true
  tasks:
        - name:  restarting httpd service
          ansible.builtin.service:
                  name: httpd.service
                  state: restarted
